version: '3.1'
services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: leokun
      POSTGRES_PASSWORD: daoshu123
      POSTGRES_DB: postgres-admin
  redis:
    container_name: redis
    image: redis:6.2.6
    volumes:
      - ./redis-data:/data
      - ./redis-logs:/logs
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
